export default {
  SET_SEARCH: 'SET_SEARCH',

  FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
  FETCH_SEARCH_FAILURE: 'FETCH_SEARCH_FAILURE',
  FETCH_SEARCH_REQUEST: 'FETCH_SEARCH_REQUEST',

  FETCH_DISCOVER_SUCCESS: 'FETCH_DISCOVER_SUCCESS',
  FETCH_DISCOVER_FAILURE: 'FETCH_DISCOVER_FAILURE',
  FETCH_DISCOVER_REQUEST: 'FETCH_DISCOVER_REQUEST',
};
